language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
jobs:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - PredictiveEcology/Require@development
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
      - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
      - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
           paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
           ')'))" >> ~/.Rprofile.site
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - covr
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - jimhester/lintr
      - PredictiveEcology/Require@development
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
      - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
      - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
           paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
           ')'))" >> ~/.Rprofile.site
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    env:
      - RSPATIAL_DEVEL=false
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - PredictiveEcology/Require@development
  # - os: linux
  #   dist: bionic
  #   r: devel
  #   env:
  #     - RSPATIAL_DEVEL=true
  #   addons:
  #     apt:
  #       sources:
  #         - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
  #       packages:
  #         - ccache
  #         - gdal-bin
  #         - libgdal-dev
  #         - libgeos-dev
  #         - libgit2-dev
  #         - libnlopt-dev
  #         - libproj-dev
  #         - libudunits2-dev
  #         - unrar
  #   services:
  #     - xvfb
  #   r_github_packages:
  #     - edzer/sp
  #     - r-spatial/sf
  #     - rspatial/raster
  #     - PredictiveEcology/Require@development
  #   r_packages:
  #     - devtools
  #   before_install:
  #     - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  #     - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  #     - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest'))" >> ~/.Rprofile.site
  #     - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
  #          paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
  #          ')'))" >> ~/.Rprofile.site
  #   before_script:
  #     - Rscript -e 'install.packages("rgdal", repos = "http://R-Forge.R-project.org")'
  #     - Rscript -e 'devtools::install_github("PredictiveEcology/Require@development", dependencies = FALSE)'
  - os: osx
    osx_image: xcode9.4
    r: oldrel
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    r_github_packages:
      - PredictiveEcology/Require@development
  - os: osx
    osx_image: xcode11.4
    r: release
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    r_github_packages:
      - PredictiveEcology/Require@development
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
