sudo: required
cache:
  - ccache
language: r
cran: https://cran.rstudio.com/
env:
  global:
    - CRAN_REPO=https://cran.rstudio.com
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
matrix:
  include:
  - os: linux
    dist: xenial
    services:
      - xvfb
    r: 3.3
    addons:
      apt:
        sources:
         - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
  - os: linux
    dist: xenial
    services:
      - xvfb
    r: 3.4
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
  - os: linux
    dist: trusty
    services:
      - xvfb
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    r_packages:
      - covr
      - devtools
    r_github_packages:
      - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
    r_packages:
    - rgdal
    - rgeos
  - os: linux
    dist: trusty
    services:
      - xvfb
    r: devel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    r_packages:
      - devtools
      - rgdal
      - rgeos
  - os: osx
    osx_image: xcode9.4
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_install:
      - brew update
      - brew install libgit2 llvm
    before_script:
      - Rscript -e "install.packages(c('rgdal', 'rgeos'), type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change

# ccache is cited here https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
